"""One module per venue. Importing this package registers all of them."""

from whatson.aggregators import (  # noqa: F401
    arcola,
    barbican,
    cafeoto,
    courtyard,
    enb,
    excel,
    genesis,
    lexington,
    oldvic,
    princecharles,
    rio,
    saatchi,
    sadlerswells,
    signaturebrew,
    sjq,
    southbank,
    southwarkparkgalleries,
    space,
    theo2,
    topsecret,
    trinitybuoywharf,
    unionchapel,
    wiltons,
    yard,
)
